import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ConditionalSiteFooter } from "@/components/landing/conditional-site-footer";
import { AppToaster } from "@/providers/app-toaster";
import { NextProgressBarProvider } from "@/providers/next-progress-bar-provider";
import { QueryProvider } from "@/providers/query-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-full antialiased">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;1,300&family=DM+Sans:wght@400;500&display=swap"
          precedence="default"
        />
      </head>
      <body className="flex min-h-full flex-col bg-background text-foreground">
        <NuqsAdapter>
          <QueryProvider>
            <NextProgressBarProvider>
              <AppToaster />
              <div className="flex min-h-full flex-1 flex-col">
                <div className="flex-1">{children}</div>
                <ConditionalSiteFooter />
              </div>
            </NextProgressBarProvider>
          </QueryProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
